### PR TITLE
refactor: use standard library in tests

### PR DESCRIPTION
**Pull request by iuioiua**

### CODE REVIEW

**Comment by kt3k** [comment]
I guess we hit the bug of Deno's test runner.

**Comment by iuioiua** [comment]
Is `time.restore()` a promise that needs to be awaited? Im away from my computer.

**Comment by kt3k** [comment]
time.restore looks sync.

If I moved `const time = new FakeTime(1469918176385);` and `time.restore()` calls inside each `t.step` (by duplicating those calls), then it seemed working..

**Comment by kt3k** [comment]
minimal repro
```js
import { FakeTime } from "https://deno.land/std@0.197.0/testing/time.ts";

Deno.test("a", async (t) => {
  const time = new FakeTime(0);
  await t.step("b", () => {});
  time.restore();
});
```

**Comment by kt3k** [comment]
https://github.com/denoland/deno/issues/20051

**Pull request merged**
